<!-- GitHub star -->
<a class="github-button" href="https://github.com/hexojs/hexo" data-icon="octicon-star" data-show-count="true" aria-label="Star hexojs/hexo on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/hexojs/hexo/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork hexojs/hexo on GitHub">Fork</a><!-- Tweet button -->
<!-- Github Button -->
<script async defer src="https://buttons.github.io/buttons.js"></script>